### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by chrischristakis** [chrischristakis/lwjgl-ponggl#1]
- [x] Abstract Shaders and VertexArray to seperate classes
- [x] Make multiple paddles and a ball
- [x] Abstract a paddle class 
- [x] Get paddle moving with key input
- [x] Use JOML and Mat to set up MVP matrix for transforms

**Comment by chrischristakis** [comment]
- [ ] Abstract a paddle class 
- [ ] Get paddle moving with key input
- [ ] Use JOML and Mat to set up MVP matrix for transforms
