### ISSUE TITLE
TODO LIST #2

### ISSUE THREAD

**Issue by chrischristakis** [chrischristakis/lwjgl-ponggl#2]
- [x] Get a ball on screen
- [x] Make ball bounce off walls
- [x] Add collision so ball bounces off paddle at random angle
- [x] Consider how to display a score
